INSERT INTO FUNCTIE (FUNCTIE_ID, SALARIU_MIN, SALARIU_MAX, DENUMIRE_FUNCTIE) VALUES ('S200', 3000, 5000, 'Specialist Relatii Cu Clientii');
INSERT INTO FUNCTIE (FUNCTIE_ID, SALARIU_MIN, SALARIU_MAX, DENUMIRE_FUNCTIE) VALUES ('S201', 3500, 6050, 'Ofiter Colectare Credite');
INSERT INTO FUNCTIE (FUNCTIE_ID, SALARIU_MIN, SALARIU_MAX, DENUMIRE_FUNCTIE) VALUES ('S203', 15000, 20000, 'Director General');
INSERT INTO FUNCTIE (FUNCTIE_ID, SALARIU_MIN, SALARIU_MAX, DENUMIRE_FUNCTIE) VALUES ('S202', 5000, 8000, 'Functionar Bancar');

COMMIT;