INSERT INTO TIPURI_DE_CREDIT (TIP_CREDIT_ID, DENUMIRE, DOBANDA_ANUALE, DURATA_MAX_LUNI) VALUES (600, 'Credit De Nevoi Personale', .04, 12);
INSERT INTO TIPURI_DE_CREDIT (TIP_CREDIT_ID, DENUMIRE, DOBANDA_ANUALE, DURATA_MAX_LUNI) VALUES (601, 'Credit Imobiliar', .06, 24);
INSERT INTO TIPURI_DE_CREDIT (TIP_CREDIT_ID, DENUMIRE, DOBANDA_ANUALE, DURATA_MAX_LUNI) VALUES (602, 'Credit Leasing', .06, 24);
INSERT INTO TIPURI_DE_CREDIT (TIP_CREDIT_ID, DENUMIRE, DOBANDA_ANUALE, DURATA_MAX_LUNI) VALUES (603, 'Credit De Investitii', .1, 120);

COMMIT;