
  CREATE TABLE "ANGAJATI" 
   (	"ANGAJAT_ID" NUMBER NOT NULL ENABLE, 
	"NUME_ANGAJAT" VARCHAR2(100) NOT NULL ENABLE, 
	"PRENUME_ANGAJAT" VARCHAR2(100) NOT NULL ENABLE, 
	"TELEFON_MUNCA" VARCHAR2(11) NOT NULL ENABLE, 
	"EMAIL_ANGAJAT" VARCHAR2(100) NOT NULL ENABLE, 
	"DATA_NASTERE" DATE NOT NULL ENABLE, 
	"DATA_ANGAJARE" DATE NOT NULL ENABLE, 
	"FUNCTIE_ID" VARCHAR2(100), 
	 CONSTRAINT "PK_ANGAJAT_ANGAJAT_ID" PRIMARY KEY ("ANGAJAT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "ANGAJATI" ADD CONSTRAINT "FK_ANGAJAT_FUNCTIE_ID" FOREIGN KEY ("FUNCTIE_ID")
	  REFERENCES "FUNCTIE" ("FUNCTIE_ID") ENABLE;