
  CREATE TABLE "CLIENTI" 
   (	"CLIENT_ID" NUMBER(5,0), 
	"NUME_CLIENT" VARCHAR2(100) NOT NULL ENABLE, 
	"PRENUME_CLIENT" VARCHAR2(100) NOT NULL ENABLE, 
	"SEX" VARCHAR2(1) NOT NULL ENABLE, 
	"TELEFON" VARCHAR2(11) NOT NULL ENABLE, 
	"EMAIL_CLIENT" VARCHAR2(100) NOT NULL ENABLE, 
	"DATA_NASTERE" DATE NOT NULL ENABLE, 
	"DATA_INREGISTRARE" DATE NOT NULL ENABLE, 
	"VENIT_LUNAR" NUMBER(10,2), 
	"CNP" VARCHAR2(13) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CLIENTI" PRIMARY KEY ("CLIENT_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UQ_CLIENTI_CNP" UNIQUE ("CNP")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CLIENTI_SEX_CH" CHECK (SEX IN ('M','F')) ENABLE
   ) ;