
  CREATE TABLE "CONTURI" 
   (	"CLIENT_ID" NUMBER NOT NULL ENABLE, 
	"IBAN" VARCHAR2(34) NOT NULL ENABLE, 
	"TIP_CONT" VARCHAR2(10) NOT NULL ENABLE, 
	"SOLD" NUMBER(10,2) NOT NULL ENABLE, 
	"DATA_DESCHIDERE" DATE NOT NULL ENABLE, 
	"CREDIT_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "UQ_CONTURI_IBAN" UNIQUE ("IBAN")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CONTURI" ADD CONSTRAINT "FK_CONTURI_CLIENT_ID" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "CLIENTI" ("CLIENT_ID") ENABLE;
  ALTER TABLE "CONTURI" ADD CONSTRAINT "FK_CONTURI_CREDIT_ID" FOREIGN KEY ("CREDIT_ID")
	  REFERENCES "CREDITE" ("CREDIT_ID") ENABLE;