
  CREATE TABLE "CREDITE" 
   (	"CREDIT_ID" NUMBER NOT NULL ENABLE, 
	"CLIENT_ID" NUMBER NOT NULL ENABLE, 
	"TIP_CREDIT_ID" NUMBER NOT NULL ENABLE, 
	"ANGAJAT_ID" NUMBER NOT NULL ENABLE, 
	"SUMA_IMPRUMUTATA" NUMBER NOT NULL ENABLE, 
	"DATA_ACORDARE" DATE NOT NULL ENABLE, 
	"DURATA_LUNI" NUMBER NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20) NOT NULL ENABLE, 
	 CONSTRAINT "PK_CREDITE_CREDIT_ID" PRIMARY KEY ("CREDIT_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "CREDITE" ADD CONSTRAINT "FK_CREDITE_ANGAJAT_ID" FOREIGN KEY ("ANGAJAT_ID")
	  REFERENCES "ANGAJATI" ("ANGAJAT_ID") ENABLE;
  ALTER TABLE "CREDITE" ADD CONSTRAINT "FK_CREDITE_CLIENT_ID" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "CLIENTI" ("CLIENT_ID") ENABLE;
  ALTER TABLE "CREDITE" ADD CONSTRAINT "FK_CREDITE_TIP_CREDIT_ID" FOREIGN KEY ("TIP_CREDIT_ID")
	  REFERENCES "TIPURI_DE_CREDIT" ("TIP_CREDIT_ID") ENABLE;