
  CREATE TABLE "FUNCTIE" 
   (	"FUNCTIE_ID" VARCHAR2(100) NOT NULL ENABLE, 
	"SALARIU_MIN" NUMBER NOT NULL ENABLE, 
	"SALARIU_MAX" NUMBER NOT NULL ENABLE, 
	"DENUMIRE_FUNCTIE" VARCHAR2(100) NOT NULL ENABLE, 
	 CONSTRAINT "PK_FUNCTIE_FUNCTIE_ID" PRIMARY KEY ("FUNCTIE_ID")
  USING INDEX  ENABLE
   ) ;