
  CREATE TABLE "RATE" 
   (	"RATA_ID" NUMBER NOT NULL ENABLE, 
	"CREDIT_ID" NUMBER NOT NULL ENABLE, 
	"DATA_SCADENTA" DATE NOT NULL ENABLE, 
	"SUMA_RATA" NUMBER(10,2) NOT NULL ENABLE, 
	"PLATITA" VARCHAR2(3) NOT NULL ENABLE, 
	"DATA_PLATA" DATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_RATE_RATA_ID" PRIMARY KEY ("RATA_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "RATE_PLATITA_CH" CHECK (PLATITA IN ('DA','NU')) ENABLE
   ) ;

  ALTER TABLE "RATE" ADD CONSTRAINT "FK_RATE_CREDIT_ID" FOREIGN KEY ("CREDIT_ID")
	  REFERENCES "CREDITE" ("CREDIT_ID") ENABLE;