
  CREATE TABLE "RESTANTE" 
   (	"RESTANTA_ID" VARCHAR2(5) NOT NULL ENABLE, 
	"CREDIT_ID" NUMBER NOT NULL ENABLE, 
	"DATA_RESTANTA" DATE NOT NULL ENABLE, 
	"SUMA_RESTANTA" NUMBER(10,2) NOT NULL ENABLE, 
	"RATA_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_RESTANTE_RESTANTA_ID" PRIMARY KEY ("RESTANTA_ID")
  USING INDEX  ENABLE
   ) ;

  ALTER TABLE "RESTANTE" ADD CONSTRAINT "FK_RESTANTE_CREDIT_ID" FOREIGN KEY ("CREDIT_ID")
	  REFERENCES "CREDITE" ("CREDIT_ID") ENABLE;
  ALTER TABLE "RESTANTE" ADD CONSTRAINT "FK_RESTANTE_RATA_ID" FOREIGN KEY ("RATA_ID")
	  REFERENCES "RATE" ("RATA_ID") ENABLE;