
  CREATE TABLE "TIPURI_DE_CREDIT" 
   (	"TIP_CREDIT_ID" NUMBER NOT NULL ENABLE, 
	"DENUMIRE" VARCHAR2(100) NOT NULL ENABLE, 
	"DOBANDA_ANUALA" NUMBER(4,2) NOT NULL ENABLE, 
	"DURATA_MAX_LUNI" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "PK_TIPURI_DE_CREDIT_TIP_CREDIT_ID" PRIMARY KEY ("TIP_CREDIT_ID")
  USING INDEX  ENABLE
   ) ;